# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Higgsfield < Formula
  desc "Higgsfield AI CLI — generate images and videos from the terminal."
  homepage "https://higgsfield.ai"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/higgsfield-ai/cli/releases/download/v0.2.1/hf_0.2.1_darwin_amd64.tar.gz"
      sha256 "9a1c489599be65d6e993c18be7f69a8ca8609b9a903429d16239544fe41179e5"

      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/higgsfield-ai/cli/releases/download/v0.2.1/hf_0.2.1_darwin_arm64.tar.gz"
      sha256 "df4f0667cbaa649b0780821defb23d6c32d9f85d67347f3c95889eab0799bef1"

      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/higgsfield-ai/cli/releases/download/v0.2.1/hf_0.2.1_linux_amd64.tar.gz"
      sha256 "e1314ec0955f6bd430249f5977ba17360823bb84b53aa5d2c08f6c93226a2949"
      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/higgsfield-ai/cli/releases/download/v0.2.1/hf_0.2.1_linux_arm64.tar.gz"
      sha256 "3ff2f837d7bd23a873aa0eda62ec48f0e7f6277f8dee0231b1b60e4e4767c451"
      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
  end

  test do
    system "#{bin}/higgsfield", "version"
  end
end
