# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Higgsfield < Formula
  desc "Higgsfield AI CLI — generate images and videos from the terminal."
  homepage "https://higgsfield.ai"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/higgsfield-ai/cli/releases/download/v1.0.1/hf_1.0.1_darwin_amd64.tar.gz"
      sha256 "8fb0387b3df9f57e88304f38343fe2979f88bfa5a165dd97ff3dbf7ed3ccfff2"

      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/higgsfield-ai/cli/releases/download/v1.0.1/hf_1.0.1_darwin_arm64.tar.gz"
      sha256 "ee8b849a1af13d657eca611f672f1c207aae086e154f0169b3ae63b4d26278e7"

      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/higgsfield-ai/cli/releases/download/v1.0.1/hf_1.0.1_linux_amd64.tar.gz"
      sha256 "fd5bc984cae553648f0d3db31f06a5dc696fa5620c6d5319f445a1653f8f4e46"
      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/higgsfield-ai/cli/releases/download/v1.0.1/hf_1.0.1_linux_arm64.tar.gz"
      sha256 "1bf1ca5ef72155bf225f44dce3cb8d9e0e38d5cd7d85d1259beeafe57c8eea75"
      define_method(:install) do
        bin.install "hf" => "higgsfield"
        bin.install_symlink "higgsfield" => "higgs"
        bin.install_symlink "higgsfield" => "hf"
      end
    end
  end

  test do
    system "#{bin}/higgsfield", "version"
  end
end
